### ISSUE TITLE
Figure out static linking of openssl

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/hello_musl#2]
Ref: https://github.com/emk/rust-musl-builder/blob/14ff0ce4bf84857e83a026eac335c4299ee8518b/Dockerfile#L72-L79

**Comment by kaushalmodi** [comment]
Thanks @xmonader for https://gitter.im/nim-lang/Nim?at=5bbe573e271506518decaf88. I need to add this to the travis config now.

```
OPENSSL_DIR=/usr/lib/musl/ \
OPENSSL_INCLUDE_DIR=/usr/lib/musl/include/ \
DEP_OPENSSL_INCLUDE=/usr/lib/musl/include/ \
OPENSSL_LIB_DIR=/usr/lib/musl/lib/ \
OPENSSL_STATIC=1 

echo "Building OpenSSL" && \
cd /tmp && \
OPENSSL_VERSION=1.0.2o && \
curl -LO "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz" && \
tar xvzf "openssl-$OPENSSL_VERSION.tar.gz" && cd "openssl-$OPENSSL_VERSION" && \
env CC=musl-gcc ./Configure no-shared no-zlib -fPIC --prefix=/usr/lib/musl linux-x86_64 && \
env C_INCLUDE_PATH=/usr/lib/musl/include/ make depend && \
make && sudo make install
```

https://gitter.im/nim-lang/Nim?at=5bbe605d435c2a518e84b00a

**Comment by kaushalmodi** [comment]
As noted at https://gitter.im/nim-lang/Nim?at=5bbe64acf659e67772938a2a, libcrypto lib also needs to be built statically.

**Comment by kaushalmodi** [comment]
https://gitter.im/nim-lang/Nim?at=5bbeda8c38449236611c33fd

**Comment by kaushalmodi** [comment]
- Works on RHEL 6.8 with openssl: https://github.com/kaushalmodi/hello_musl/tree/ssl-works-rhel-6-8, but fails on Travis

**Comment by kaushalmodi** [comment]
- Issue for openssl + musl build on Travis: https://github.com/travis-ci/travis-ci/issues/10226

**Comment by kaushalmodi** [comment]
Libressl + musl build fails on Travis too: https://travis-ci.org/kaushalmodi/hello_musl/builds/440311276#L1420

```
  CC       compat/libcompatnoopt_la-explicit_bzero.lo
compat/getentropy_linux.c:31:26: fatal error: linux/sysctl.h: No such file or directory
 #include <linux/sysctl.h>
                          ^
compilation terminated.
make[2]: *** [compat/getentropy_linux.lo] Error 1
```

Ref: https://gitter.im/nim-lang/Nim?at=5bbf9370bbdc0b250524cf46

**Comment by kaushalmodi** [comment]
Another tip by leorize: https://gitter.im/nim-lang/Nim?at=5bc00dfebbdc0b2505282b3d

**Comment by kaushalmodi** [comment]
**Finally** got openssl+musl to compile on Travis!!

The *magic* solution: https://github.com/kaushalmodi/hello_musl/blob/eecd53e0e3a9675372b16763679ff0609055b30f/config.nims#L83-L86

But libressl+musl on Travis still fails: 
- https://github.com/kaushalmodi/hello_musl/tree/libressl
- https://travis-ci.org/kaushalmodi/hello_musl/builds/440709973#L1419

**Comment by kaushalmodi** [comment]
Actually libressl+musl started building on Travis after the same two -dirafter switches!

Now optimize the libressl build using:

```
<leorize> small tips:
<leorize> build only the components that you use
<leorize> like this
<leorize> make -C crypto
<leorize> make -C ssl
<leorize> then install them with make -C crypto install
```


Ref: https://gitter.im/nim-lang/Nim?at=5bbf7b7b435c2a518e8ccbbe
